"""empty message

Revision ID: 5998e9ee193
Revises: 4c435b133c9f
Create Date: 2014-06-18 01:17:17.735502

"""

# revision identifiers, used by Alembic.
revision = '5998e9ee193'
down_revision = '4c435b133c9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    ### end Alembic commands ###
